# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PayModule' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PayModule


	pod 'WechatOpenSDK'
    pod 'AFNetwork', '~> 0.1.0'


  target 'PayModule-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PayModuleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

